[project]
name = "auction-service"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "dotenv>=0.9.9",
    "grpcio>=1.76.0",
    "psycopg2-binary>=2.9.11",
    "sqlalchemy>=2.0.44",
]
